### ISSUE TITLE
Kodiak 100 ignition toggle not working

### ISSUE THREAD

**Issue by avdl72** [MobiFlight/MobiFlight-WASM-Module#12]
The switches used to startup the Kodiak 100 are working from my stream deck except the ignition switch KODIAK_100_IGNITION_SWITCH_TOGGLE.

I configured all the switches with MOBIFLIGHT_ in front. So in this case: MOBIFLIGHT_KODIAK_100_IGNITION_SWITCH_TOGGLE.
But the event command is not working.

Can someone advice me what to do to get this one working?

**Comment by DocMoebiuz** [comment]
I am sorry that I didn't see this issue. This sounds like a events.txt problem. events.txt files contain presets that come from HubHop. 

The support for this approach has ended last year. We now only use dynamically registered events. Label names don't matter anymore.

Please reach out on our discord in case this is still an issue for you.
