### ISSUE TITLE
Custom Client opens prior to MobiFlight Connector will crash the MSFS

### ISSUE THREAD

**Issue by cpuwolf** [MobiFlight/MobiFlight-WASM-Module#15]
The workaround is to defer Custom Client open timing.

I do believe there is potential race condition

**Comment by DocMoebiuz** [comment]
This should not be the case anymore. MF Connector now itself is a Client and we have not experienced any such issues.

**Comment by cpuwolf** [comment]
Good to know, Thank you DocMoebiuz 谢谢
