### ISSUE TITLE
Add build and install instructions

### ISSUE THREAD

**Issue by winternet-studio** [MobiFlight/MobiFlight-WASM-Module#2]
How do I install this? I don't need the whole MobilFlight Connector application, I just need this standalone WASM module.

**Comment by MobiFlight-Admin** [comment]
the easiest method is to download the mobiflight connector and let it install the wasm module. then you could delete mobiflight connector.

**Comment by MobiFlight-Admin** [comment]
i can add a compiled version as release.

**Comment by winternet-studio** [comment]
That would be nice - thanks.

**Comment by mpaperno** [comment]
I just downloaded it from https://github.com/MobiFlight/MobiFlight-Connector/tree/main/MSFS2020-module  (well, as part of the overall source code zip file).  Extracted and put the `mobiflight-event-module`  folder into my MSFS Community directory.

Did I cheat?  :)  

Thanks for the work Sebastian!
-Max

**Comment by DocMoebiuz** [comment]
@mpaperno  haha - you are right. that's one way to do it.

**Comment by Koseng** [comment]
Releases now contain the wasm module.
