### ISSUE TITLE
[REQUEST] Full commands for G1000 NXi

### ISSUE THREAD

**Issue by keukenrol** [MobiFlight/MobiFlight-WASM-Module#28]
Hi

I am using the mobiflight wasm module commands together with the python SimConnect module. In the events.txt file I noticed missing commands for the AS1000 autopilot knobs. While these do work with the default simulator autopilot commands, I was wondering if there would be specific ones for the AS1000 or working title G1000 NXi.
Same for the MID panel, currently only the COM1, COM1 mic, COM2, COM2 mic and COM3, COM3 mic are listed. Are there plans to support the full panel? Thanks!

**Comment by Koseng** [comment]
Hi,
no events.txt necessary any more. And for advanced stuff:
https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension

**Comment by keukenrol** [comment]
Okay, is it possible to clarify how I would pass button press commands without events?
Currently, I am using commands
`command = "MobiFlight.AS1000_MFD_NAV_Push"`
which are sent via a SimConnect link. 
```
sim_event = Event(command.encode('utf-8'), sm)
    # Call the Event.
    sim_event()
```

**Comment by DocMoebiuz** [comment]
Hi @keukenrol that's outlined in the https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension?tab=readme-ov-file#example here.

events.txt is not supported anymore. You can always add your own defintions inside the events.user.txt - so if you have to stick to that approach then there is a solution for you.

I will close this issue for now.
