### ISSUE TITLE
MSFS micro stuttering due to reading/monitoring too many Simvars

### ISSUE THREAD

**Issue by cpuwolf** [MobiFlight/MobiFlight-WASM-Module#9]
Great Thanks to MobiFlight, I found I have no reason to develop a new module, except to reuse mobiflight. it is a great gift of open source community.

After I deeply developed a client based on your module, I found a serious performance issue.

micro stuttering is seen regularly every xxx ms. a sudden frame drop regularly be seen in below screenshot

From a user experience, it is not acceptable.

![shutters](https://user-images.githubusercontent.com/1320329/166190209-7e6efc1f-e157-4ea6-9a31-06c064ce0cd8.gif)

By removing Community\mobiflight-event-module,  micro stuttering is gone.

Background: I am developing a SimConnect client calling MobiFlight module.

**Comment by DocMoebiuz** [comment]
with how many values does this happen? I haven't encountered this problem yet in my setups.

**Comment by cpuwolf** [comment]
@DocMoebiuz I have around 40 SimVars to be monitored. I have confirmed it will cause micro stuttering. I did CtrlX/CtrlV mobiflight-event-module at least 10 times. I am sure it has side effect on MSFS performace

**Comment by cpuwolf** [comment]
I have uploaded a video to show you what was happened
https://youtu.be/uX5df6sIRN4

**Comment by Koseng** [comment]
Hi, 
nice video with sound effects ;-).

I will do some tests as well.

An issue on the mobiflight WASM side is just one possibility.

Problems might also be caused on the simconnect client side:
- There is only one callback thread with the DispatchProc callback function. If you're code in the callback function is too slow and takes too long processing the callbacks, this might create problems as well.
- If your code receives too many values and  you do some heavy calculations, you could use too much CPU in your simconnect client which also might cause stutters in the sim. 

Some tests will show.

**Comment by Koseng** [comment]
Ok I did tests and can confirm. It also happens if the external simconnect client is disconnected and the WASM just does its work with the registered variables.

On my system:
- Until 50 simple variables there is barely anything noticeable
- With 70 variables I have stutter every 3s
- With 80 variables I have stutter every 2.5s
- With 100 variables I have stutter every 2s
- Above 100 it goes crazy and it is a stutterfest. It seems there some threshold is reached.

**Comment by cpuwolf** [comment]
> Ok I did tests and can confirm. It also happens if the external simconnect client is disconnected and the WASM just does its work with the registered variables.
> 
> On my system:
> 
> * Until 50 simple variables there is barely anything noticeable
> * With 70 variables I have stutter every 3s
> * With 80 variables I have stutter every 2.5s
> * With 100 variables I have stutter every 2s
> * Above 100 it goes crazy and it is a stutterfest. It seems there some threshold is reached.

it is exactly matching my testing, micro shutter will be there once the client has registered these values in Mobi. Thanks for confirmation
